<?php
/* Include SWIG autogenerated proxies */
require_once __DIR__ . '/../build/SimplePcap.php';

/* Validate cli arguments */
if ($argc != 6) {
    echo "Use: $argv[0]: <interfaceName> <libpcapFilterExpression> <snapLen> <timeout> <file containing raw packet data>\n";
    exit(250);
}

/* Get cli arguments */
$device = $argv[1];
$filter = $argv[2];
$snapLen =  $argv[3];
$timeout = $argv[4];
$file = $argv[5];

/* Get a SimplePcapObject */
$simplePcap = new SimplePcap($device, $filter, $snapLen, $timeout);
$contents = file_get_contents($file);

$totalBytesSent = $simplePcap->send($contents);
echo "Injected $totalBytesSent in: $device\n";

